### PR TITLE
Aci 65:Publishing the resource Added event after  the initial plugin status request 

### LINKED ISSUE #65: ACI plugin pod needs to be restarted to get the fabric added event
Pre-req:

ODIM and ACI plugin integration is completed

steps to reproduce:

1.Deploy the one node odim K8cluster with ACI plugin

2. Add the ACI plugin 

3.Observed that fabric added event is not received in fabrics.log

4.Restart the ACI plugin pod

5.Received the fabric added event

Expected Result:

Without restart of aci plugin pod, fabric added event should be received

### PR DESCRIPTION
**Pull request by jeevan-kamkar**
closes #65

### CODE REVIEW

File: caphandler/pluginStatus.go [hunk 1]
```diff
@@ -70,3 +81,35 @@ func GetPluginStartup(ctx iris.Context) {
 	// TODO: implementation pending
 	ctx.StatusCode(http.StatusNotImplemented)
 }
+
+func publishResourceAddedEvent() {
```
Comment (Bharath-KKB) [inline caphandler/pluginStatus.go:85]: rename to publishFabricAddedEvent, as this is all the func does or will do in future

**Review by Bharath-KKB — CHANGES_REQUESTED** [review]
address comments

File: caphandler/pluginStatus.go (hunk 1 above)
Comment (jeevan-kamkar) [reply caphandler/pluginStatus.go]: updated

**Review by Bharath-KKB — APPROVED** [review]

**Review by lakkundipooja — APPROVED** [review]
